######################################################################
# Automatically generated by qmake (2.00a) Wed Jan 11 02:39:20 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .


# Input
HEADERS += SortedTableView.h
SOURCES += main.cpp SortedTableView.cpp
